apiVersion: v1
kind: Service
metadata:
  name: vibe-app-stable
  namespace: vibe
  labels:
    app: vibe-app

spec:
  selector:
    app: vibe-app

  ports:
    - name: http
      port: 80
      targetPort: 8000
